package cli

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"strings"
	"time"

	"github.com/Ricardo-M-L/mcphub/internal/store"
	"github.com/Ricardo-M-L/mcphub/internal/ui"
	"github.com/spf13/cobra"
)

var sdkgenLang string

var sdkgenCmd = &cobra.Command{
	Use:   "sdkgen <server-name>",
	Short: "Generate SDK code from an MCP server's tool schemas",
	Long: `Connect to an installed MCP server, discover its tools, and generate
typed client code in TypeScript or Python.

Examples:
  mcphub sdkgen io.github.xxx/server-filesystem --lang typescript
  mcphub sdkgen io.github.xxx/server-filesystem --lang python`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		name := args[0]

		lf, err := store.Load()
		if err != nil {
			return err
		}

		pkg, ok := lf.Get(name)
		if !ok {
			// Try partial match
			for k, p := range lf.Packages {
				if strings.Contains(k, name) || strings.Contains(p.Name, name) {
					pkg = p
					ok = true
					break
				}
			}
			if !ok {
				return fmt.Errorf("server %q is not installed. Run 'mcphub install' first", name)
			}
		}

		// Start the server and get tool list
		ui.PrintInfo("Connecting to server to discover tools...")

		command := "npx"
		cmdArgs := []string{"-y", pkg.Identifier}
		if pkg.RuntimeHint == "uvx" {
			command = "uvx"
			cmdArgs = []string{pkg.Identifier}
		}

		if pkg.Identifier == "" {
			return fmt.Errorf("cannot start server: no identifier found")
		}

		ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
		defer cancel()

		serverCmd := exec.CommandContext(ctx, command, cmdArgs...)
		serverCmd.Env = os.Environ()
		for k, v := range pkg.EnvVars {
			serverCmd.Env = append(serverCmd.Env, fmt.Sprintf("%s=%s", k, v))
		}

		stdin, err := serverCmd.StdinPipe()
		if err != nil {
			return fmt.Errorf("failed to create stdin: %w", err)
		}
		stdout, err := serverCmd.StdoutPipe()
		if err != nil {
			return fmt.Errorf("failed to create stdout: %w", err)
		}
		serverCmd.Stderr = nil

		if err := serverCmd.Start(); err != nil {
			return fmt.Errorf("failed to start server: %w", err)
		}
		defer func() {
			stdin.Close()
			serverCmd.Process.Kill()
			serverCmd.Wait()
		}()

		// Send initialize
		initReq, _ := json.Marshal(map[string]interface{}{
			"jsonrpc": "2.0", "id": 1, "method": "initialize",
			"params": map[string]interface{}{
				"protocolVersion": "2025-03-26",
				"capabilities":   map[string]interface{}{},
				"clientInfo":     map[string]interface{}{"name": "mcphub-sdkgen", "version": "0.2.0"},
			},
		})
		stdin.Write(append(initReq, '\n'))

		scanner := bufio.NewScanner(stdout)
		if !scanner.Scan() {
			return fmt.Errorf("no response from server")
		}

		// Send tools/list
		toolsReq, _ := json.Marshal(map[string]interface{}{
			"jsonrpc": "2.0", "id": 2, "method": "tools/list",
		})
		stdin.Write(append(toolsReq, '\n'))

		if !scanner.Scan() {
			return fmt.Errorf("no tools/list response")
		}
		toolsResp := scanner.Text()

		var result struct {
			Result struct {
				Tools []ToolSchema `json:"tools"`
			} `json:"result"`
		}
		if err := json.Unmarshal([]byte(toolsResp), &result); err != nil {
			return fmt.Errorf("failed to parse tools: %w", err)
		}

		tools := result.Result.Tools
		if len(tools) == 0 {
			return fmt.Errorf("server has no tools")
		}

		ui.PrintSuccess(fmt.Sprintf("Found %d tools", len(tools)))

		// Generate SDK
		var output string
		switch sdkgenLang {
		case "typescript", "ts":
			output = generateTypeScript(name, tools)
		case "python", "py":
			output = generatePython(name, tools)
		default:
			output = generateTypeScript(name, tools)
		}

		fmt.Println(output)
		return nil
	},
}

// ToolSchema represents an MCP tool definition.
type ToolSchema struct {
	Name        string                 `json:"name"`
	Description string                 `json:"description"`
	InputSchema map[string]interface{} `json:"inputSchema"`
}

func generateTypeScript(serverName string, tools []ToolSchema) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("// Auto-generated SDK for %s\n", serverName))
	sb.WriteString("// Generated by mcphub sdkgen\n\n")
	sb.WriteString("import { Client } from '@modelcontextprotocol/sdk/client/index.js';\n")
	sb.WriteString("import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';\n\n")

	// Generate interface for each tool
	for _, tool := range tools {
		sb.WriteString(fmt.Sprintf("/** %s */\n", tool.Description))

		// Generate input type
		typeName := toPascalCase(tool.Name) + "Input"
		sb.WriteString(fmt.Sprintf("export interface %s {\n", typeName))
		if props, ok := tool.InputSchema["properties"].(map[string]interface{}); ok {
			for propName, propDef := range props {
				propMap, _ := propDef.(map[string]interface{})
				tsType := jsonTypeToTS(propMap)
				desc := ""
				if d, ok := propMap["description"].(string); ok {
					desc = fmt.Sprintf(" // %s", d)
				}
				sb.WriteString(fmt.Sprintf("  %s?: %s;%s\n", propName, tsType, desc))
			}
		}
		sb.WriteString("}\n\n")
	}

	// Generate client class
	sb.WriteString("export class MCPClient {\n")
	sb.WriteString("  private client: Client;\n\n")
	sb.WriteString("  constructor(private transport: StdioClientTransport) {\n")
	sb.WriteString("    this.client = new Client({ name: 'sdk-client', version: '1.0.0' });\n")
	sb.WriteString("  }\n\n")
	sb.WriteString("  async connect() {\n")
	sb.WriteString("    await this.client.connect(this.transport);\n")
	sb.WriteString("  }\n\n")

	for _, tool := range tools {
		typeName := toPascalCase(tool.Name) + "Input"
		sb.WriteString(fmt.Sprintf("  /** %s */\n", tool.Description))
		sb.WriteString(fmt.Sprintf("  async %s(params: %s) {\n", toCamelCase(tool.Name), typeName))
		sb.WriteString(fmt.Sprintf("    return this.client.callTool({ name: '%s', arguments: params });\n", tool.Name))
		sb.WriteString("  }\n\n")
	}

	sb.WriteString("}\n")
	return sb.String()
}

func generatePython(serverName string, tools []ToolSchema) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Auto-generated SDK for %s\n", serverName))
	sb.WriteString("# Generated by mcphub sdkgen\n\n")
	sb.WriteString("from dataclasses import dataclass\n")
	sb.WriteString("from typing import Any, Optional\n\n")

	// Generate dataclass for each tool
	for _, tool := range tools {
		className := toPascalCase(tool.Name) + "Input"
		sb.WriteString(fmt.Sprintf("@dataclass\nclass %s:\n", className))
		sb.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n", tool.Description))
		if props, ok := tool.InputSchema["properties"].(map[string]interface{}); ok {
			for propName, propDef := range props {
				propMap, _ := propDef.(map[string]interface{})
				pyType := jsonTypeToPython(propMap)
				sb.WriteString(fmt.Sprintf("    %s: Optional[%s] = None\n", toSnakeCase(propName), pyType))
			}
		} else {
			sb.WriteString("    pass\n")
		}
		sb.WriteString("\n\n")
	}

	// Generate client class
	sb.WriteString(fmt.Sprintf("class %sClient:\n", toPascalCase(strings.ReplaceAll(serverName, "/", "_"))))
	sb.WriteString("    \"\"\"MCP client SDK\"\"\"\n\n")
	sb.WriteString("    def __init__(self, session):\n")
	sb.WriteString("        self.session = session\n\n")

	for _, tool := range tools {
		sb.WriteString(fmt.Sprintf("    async def %s(self, **kwargs) -> Any:\n", toSnakeCase(tool.Name)))
		sb.WriteString(fmt.Sprintf("        \"\"\"%s\"\"\"\n", tool.Description))
		sb.WriteString(fmt.Sprintf("        return await self.session.call_tool('%s', arguments=kwargs)\n\n", tool.Name))
	}

	return sb.String()
}

func toPascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' || r == '.' })
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func toCamelCase(s string) string {
	p := toPascalCase(s)
	if len(p) > 0 {
		return strings.ToLower(p[:1]) + p[1:]
	}
	return p
}

func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result.WriteByte('_')
		}
		result.WriteRune(r)
	}
	return strings.ToLower(result.String())
}

func jsonTypeToTS(prop map[string]interface{}) string {
	t, _ := prop["type"].(string)
	switch t {
	case "string":
		return "string"
	case "number", "integer":
		return "number"
	case "boolean":
		return "boolean"
	case "array":
		return "any[]"
	case "object":
		return "Record<string, any>"
	default:
		return "any"
	}
}

func jsonTypeToPython(prop map[string]interface{}) string {
	t, _ := prop["type"].(string)
	switch t {
	case "string":
		return "str"
	case "number":
		return "float"
	case "integer":
		return "int"
	case "boolean":
		return "bool"
	case "array":
		return "list"
	case "object":
		return "dict"
	default:
		return "Any"
	}
}

func init() {
	sdkgenCmd.Flags().StringVar(&sdkgenLang, "lang", "typescript", "Output language (typescript, python)")
}
